"""
Intraday quote poller — runs Mon–Fri at 9:30, 11:00, 12:30, 14:00, 15:30 ET.

Polls the union of watchlist symbols and open-position symbols, fetching each
quote exactly once, then runs two independent evaluators over the shared price map:

  1. Opportunity conditions (watchlist symbols) — "here's a trade idea"
  2. Position conditions    (open positions)    — "a trade you hold hit its exit"

Opportunity alert types generated (category='opportunity'):
  price_below_lower_bb — current price < bb_lower
  price_above_upper_bb — current price > bb_upper
  price_below_ema8     — current price < ema_8
  price_above_ema8     — current price > ema_8

Position alert types are generated by position_monitor.py (category='position').

Public API:
  fetch_intraday_quote(symbol) -> float
  evaluate_intraday_conditions(...) -> tuple[list[dict], int]
  run_intraday_poll() -> dict
"""

import logging
from datetime import date, datetime, timezone

import yfinance as yf

from app.database import get_client
from app.services import positions as pos_svc
from app.services.indicator_cache import get_latest_snapshots
from app.services.position_monitor import run_position_monitor
from app.services.scanner import _get_watchlist_symbols

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Quote fetch
# ---------------------------------------------------------------------------

def fetch_intraday_quote(symbol: str) -> float:
    """
    Return the most-recent trade price for symbol using yfinance.
    Raises ValueError if the price cannot be retrieved.
    """
    info = yf.Ticker(symbol).fast_info
    price = info.get("last_price") or info.get("lastPrice")
    if price is None or price != price:  # NaN check
        raise ValueError(f"No intraday price available for {symbol}")
    return float(price)


# ---------------------------------------------------------------------------
# Dedup helper
# ---------------------------------------------------------------------------

def _get_existing_intraday_alerts_today(
    symbols: list[str], today: date
) -> set[tuple[str, str]]:
    """
    Return (symbol, alert_type) pairs already inserted today for the given symbols.
    Reuses the same alerts table as the EOD scanner — no duplicate per calendar day.

    Filtered to category='opportunity': position alerts live in the same table but
    dedup on position_id, and must not be able to suppress an opportunity alert
    (or be suppressed by one) just because they share a symbol.
    """
    if not symbols:
        return set()
    res = (
        get_client()
        .table("alerts")
        .select("symbol,alert_type")
        .in_("symbol", symbols)
        .eq("category", "opportunity")
        .eq("date", today.isoformat())
        .execute()
    )
    return {(row["symbol"], row["alert_type"]) for row in res.data}


# ---------------------------------------------------------------------------
# Condition evaluation (exported for unit tests)
# ---------------------------------------------------------------------------

def evaluate_intraday_conditions(
    symbol:        str,
    current_price: float,
    snapshot:      dict,
    existing:      set[tuple[str, str]],
    today:         date,
) -> tuple[list[dict], int]:
    """
    Evaluate the four intraday price-vs-snapshot conditions for one symbol.

    Returns:
        (new_alerts, skipped_count)
        new_alerts    — alert dicts ready to insert (deduped against existing)
        skipped_count — conditions that fired but were already in existing
    """
    alerts:  list[dict] = []
    skipped: int        = 0

    bb_upper = snapshot.get("bb_upper")
    bb_lower = snapshot.get("bb_lower")
    ema_8    = snapshot.get("ema_8")

    def _add(alert_type: str, details: dict) -> None:
        nonlocal skipped
        if (symbol, alert_type) in existing:
            skipped += 1
            return
        alerts.append({
            "symbol":           symbol,
            "date":             today.isoformat(),
            "alert_type":       alert_type,
            "category":         "opportunity",
            "price_at_trigger": current_price,
            "details":          details,
            "acknowledged":     False,
        })

    if bb_lower is not None and current_price < float(bb_lower):
        _add("price_below_lower_bb", {"bb_lower": round(float(bb_lower), 4)})

    if bb_upper is not None and current_price > float(bb_upper):
        _add("price_above_upper_bb", {"bb_upper": round(float(bb_upper), 4)})

    if ema_8 is not None and current_price < float(ema_8):
        _add("price_below_ema8", {"ema_8": round(float(ema_8), 4)})

    if ema_8 is not None and current_price > float(ema_8):
        _add("price_above_ema8", {"ema_8": round(float(ema_8), 4)})

    return alerts, skipped


# ---------------------------------------------------------------------------
# Poll orchestrator
# ---------------------------------------------------------------------------

def run_intraday_poll() -> dict:
    """
    Intraday poll pipeline:
      1. Load symbols: watchlist ∪ open-position symbols
      2. Fetch current price for each (yfinance fast_info)
      3. Evaluate opportunity conditions for watchlist symbols (deduped)
      4. Hand the same price map to the position monitor for open positions
      5. Insert new alerts

    Quotes are fetched once for the union and shared between both evaluators.
    An open position can be in a symbol that is NOT on the watchlist — you may
    have removed it after entering — and those positions still have to be
    monitored, so polling the watchlist alone is not enough.

    Returns a summary dict.
    """
    started_at = datetime.now(timezone.utc)
    logger.info("Intraday poll starting")

    watchlist_symbols = _get_watchlist_symbols()
    position_symbols  = pos_svc.get_open_position_symbols()
    all_symbols       = sorted(set(watchlist_symbols) | set(position_symbols))

    if not all_symbols:
        logger.info("Intraday poll: nothing on the watchlist and no open positions — skipping")
        return {
            "symbols_polled": 0,
            "alerts_created": 0,
            "alerts_skipped": 0,
            "failed": 0,
            "positions_monitored": 0,
            "position_alerts_created": 0,
            "stops_trailed": 0,
            "started_at": started_at.isoformat(),
        }

    today = date.today()

    # Fetch current prices — collect failures, don't abort
    prices: dict[str, float] = {}
    failed = 0
    for symbol in all_symbols:
        try:
            prices[symbol] = fetch_intraday_quote(symbol)
        except Exception as exc:
            logger.warning("Intraday quote fetch failed for %s: %s", symbol, exc)
            failed += 1

    if not prices:
        logger.warning("Intraday poll: all quote fetches failed")
        return {
            "symbols_polled": len(all_symbols),
            "alerts_created": 0,
            "alerts_skipped": 0,
            "failed": failed,
            "positions_monitored": 0,
            "position_alerts_created": 0,
            "stops_trailed": 0,
            "started_at": started_at.isoformat(),
        }

    # --- Opportunity alerts: watchlist symbols only -------------------------
    # A symbol held as a position but off the watchlist is deliberately not
    # evaluated for opportunity conditions — you're already in it, so "here's an
    # idea" alerts would be noise.
    watchlist_prices = {s: p for s, p in prices.items() if s in set(watchlist_symbols)}

    snapshots   = get_latest_snapshots(list(watchlist_prices.keys()))
    snap_by_sym = {s["symbol"]: s for s in snapshots}
    existing    = _get_existing_intraday_alerts_today(list(watchlist_prices.keys()), today)

    new_alerts: list[dict] = []
    total_skipped = 0
    for symbol, price in watchlist_prices.items():
        snap = snap_by_sym.get(symbol)
        if snap is None:
            logger.debug("No snapshot for %s — skipping intraday evaluation", symbol)
            continue
        fired, skipped = evaluate_intraday_conditions(
            symbol=symbol,
            current_price=price,
            snapshot=snap,
            existing=existing,
            today=today,
        )
        new_alerts.extend(fired)
        total_skipped += skipped

    if new_alerts:
        get_client().table("alerts").insert(new_alerts).execute()

    # --- Position alerts: open positions, sharing the same quotes ------------
    try:
        pos_summary = run_position_monitor(prices)
    except Exception as exc:
        logger.error("Position monitor failed during intraday poll: %s", exc, exc_info=True)
        pos_summary = {"positions_monitored": 0, "alerts_created": 0, "stops_trailed": 0}

    logger.info(
        "Intraday poll complete — %d polled, %d opportunity alert(s), "
        "%d dedup-skipped, %d failed; %d position(s) monitored, %d position alert(s)",
        len(all_symbols), len(new_alerts), total_skipped, failed,
        pos_summary["positions_monitored"], pos_summary["alerts_created"],
    )

    return {
        "symbols_polled": len(all_symbols),
        "alerts_created": len(new_alerts),
        "alerts_skipped": total_skipped,
        "failed": failed,
        "positions_monitored":     pos_summary["positions_monitored"],
        "position_alerts_created": pos_summary["alerts_created"],
        "stops_trailed":           pos_summary["stops_trailed"],
        "started_at": started_at.isoformat(),
    }
